import { LogOut, MapPin, Package } from 'lucide-react';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { api, useGetOrderQuery, useGetOrdersQuery, useLogoutMutation, useMeQuery } from '../app/api';
import { money } from '../app/format';
import { ProductImage } from '../components/ProductCard';
import { Seo } from '../components/Seo';

const OrderDetail = () => { const { id = '' } = useParams(); const { data: order } = useGetOrderQuery(id); if (!order) return <div className="page-loading">Loading order…</div>; return <section><Link to="/account/orders">← All orders</Link><div className="account-heading"><div><p className="eyebrow">{order.orderNumber}</p><h2>Order details</h2></div><span className={`status ${order.fulfillmentStatus}`}>{order.fulfillmentStatus}</span></div>{order.items.map((item) => <div className="account-order-line" key={item.variantId}><ProductImage src={item.image} alt={item.name}/><div><h3>{item.name}</h3><p>{item.variantName} × {item.quantity}</p></div><strong>{money(item.lineTotalCents)}</strong></div>)}<div className="account-total">Total <strong>{money(order.totals.grandTotalCents)}</strong></div><h3>Shipping to</h3><p>{order.shippingAddress.recipient}<br/>{order.shippingAddress.line1}<br/>{order.shippingAddress.city}, {order.shippingAddress.region} {order.shippingAddress.postalCode}</p></section>; };
const Orders = () => { const { data } = useGetOrdersQuery(); return <section><h2>Order history</h2>{data?.length ? data.map((order) => <Link className="order-row" to={`/account/orders/${order._id}`} key={order._id}><div><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleDateString()}</small></div><span className={`status ${order.fulfillmentStatus}`}>{order.fulfillmentStatus}</span><strong>{money(order.totals.grandTotalCents)}</strong></Link>) : <div className="empty"><Package/><h3>No orders yet</h3><Link to="/shop">Start shopping</Link></div>}</section>; };
export default function Account() { const { data: user, isLoading } = useMeQuery(); const [logout, logoutState] = useLogoutMutation(); const [logoutError, setLogoutError] = useState(''); const dispatch = useDispatch(); const navigate = useNavigate(); const signOut = async () => { setLogoutError(''); try { await logout().unwrap(); dispatch(api.util.resetApiState()); navigate('/', { replace: true }); } catch { setLogoutError('Sign out failed. Please check your connection and try again.'); } }; if (!isLoading && !user) return <Navigate to="/login?next=/account" replace/>; if (!user) return <div className="page-loading">Loading account…</div>; return <main className="account-page"><Seo title="My Account | Wellora Market" description="Manage your Wellora profile, addresses, and orders."/><aside><p className="eyebrow">My Wellora</p><h1>{user.firstName} {user.lastName}</h1><nav><Link to="/account/orders"><Package/> Orders</Link><Link to="/account/addresses"><MapPin/> Addresses</Link>{['admin', 'manager'].includes(user.role) && <Link to="/admin">Admin dashboard</Link>}<button onClick={signOut} disabled={logoutState.isLoading}><LogOut/> {logoutState.isLoading ? 'Signing out…' : 'Sign out'}</button></nav>{logoutError && <p className="form-error" role="alert">{logoutError}</p>}</aside><div className="account-content"><Routes><Route index element={<Navigate to="orders" replace/>}/><Route path="orders" element={<Orders/>}/><Route path="orders/:id" element={<OrderDetail/>}/><Route path="addresses" element={<section><h2>Saved addresses</h2>{user.addresses.length ? user.addresses.map((address, i) => <article className="address" key={i}><strong>{address.label ?? 'Address'}</strong><p>{address.recipient}<br/>{address.line1}<br/>{address.city}, {address.region} {address.postalCode}</p></article>) : <p>No saved addresses.</p>}</section>}/></Routes></div></main>; }