import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useLoginMutation, useRegisterMutation } from '../app/api';
import { apiMessage } from '../app/format';
import { Seo } from '../components/Seo';

export default function Auth({ mode }: { mode: 'login' | 'register' }) {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [login, loginState] = useLoginMutation(); const [register, registerState] = useRegisterMutation(); const [error, setError] = useState(''); const busy = loginState.isLoading || registerState.isLoading;
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { if (mode === 'login') await login({ email: String(data.email), password: String(data.password) }).unwrap(); else await register({ firstName: String(data.firstName), lastName: String(data.lastName), email: String(data.email), password: String(data.password) }).unwrap(); navigate(params.get('next') ?? '/account'); } catch (value) { setError(apiMessage(value)); } };
  return <main className="auth-page"><Seo title={`${mode === 'login' ? 'Sign In' : 'Create Account'} | Wellora Market`} description="Access your Wellora Market account, orders, addresses, and wishlist."/><section><p className="eyebrow">{mode === 'login' ? 'Welcome back' : 'A better shelf starts here'}</p><h1>{mode === 'login' ? 'Sign in to Wellora' : 'Create your account'}</h1><p>{mode === 'login' ? 'Access your bag, wishlist, and order history.' : 'Save favorites, checkout faster, and follow every order.'}</p><form onSubmit={submit}>{mode === 'register' && <div className="field-row"><label>First name<input name="firstName" required minLength={2}/></label><label>Last name<input name="lastName" required minLength={2}/></label></div>}<label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} minLength={8} required/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form>{mode === 'login' ? <><Link className="subtle-link" to="/forgot-password">Forgot your password?</Link><p>New here? <Link to="/register">Create an account</Link></p></> : <p>Already have an account? <Link to="/login">Sign in</Link></p>}</section><img src="https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1000&q=85" alt="Beauty and personal care products arranged on a warm surface"/></main>;
}