import { Minus, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useApplyCouponMutation, useGetCartQuery, useMeQuery, useRemoveCartMutation, useUpdateCartMutation } from '../app/api';
import { apiMessage, money } from '../app/format';
import { ProductImage } from '../components/ProductCard';
import { Seo } from '../components/Seo';

export default function Cart() {
  const { data: user } = useMeQuery(); const { data: cart, isLoading } = useGetCartQuery(undefined, { skip: !user }); const [update] = useUpdateCartMutation(); const [remove] = useRemoveCartMutation(); const [apply] = useApplyCouponMutation(); const [code, setCode] = useState(''); const [message, setMessage] = useState('');
  if (!user) return <main className="empty"><h1>Your bag is waiting.</h1><p>Sign in to access your saved cart across devices.</p><Link className="button" to="/login?next=/cart">Sign in</Link></main>; if (isLoading) return <div className="page-loading">Loading your bag…</div>;
  if (!cart?.items.length) return <main className="empty"><Seo title="Your Bag | Wellora Market" description="Review your Wellora Market shopping bag."/><h1>Your bag is empty.</h1><p>Explore useful everyday care and find your next staple.</p><Link className="button" to="/shop">Shop the collection</Link></main>;
  const coupon = async (e: React.FormEvent) => { e.preventDefault(); try { await apply(code).unwrap(); setMessage('Coupon applied.'); } catch (error) { setMessage(apiMessage(error)); } };
  return <main className="cart-page"><Seo title="Your Bag | Wellora Market" description="Review your Wellora Market shopping bag."/><h1>Your bag</h1><div className="cart-layout"><section className="cart-lines">{cart.items.map((item) => <article className="cart-line" key={item.variantId}><ProductImage src={item.image} alt={item.name}/><div><h2>{item.name}</h2><p>{item.variantName} · {item.sku}</p><p className="price">{money(item.unitPriceCents)}</p><div className="stepper small"><button onClick={() => item.quantity > 1 ? update({ variantId: item.variantId, quantity: item.quantity - 1 }) : remove(item.variantId)} aria-label="Decrease quantity"><Minus/></button><span>{item.quantity}</span><button onClick={() => update({ variantId: item.variantId, quantity: item.quantity + 1 })} aria-label="Increase quantity"><Plus/></button></div></div><button className="icon-button" onClick={() => remove(item.variantId)} aria-label={`Remove ${item.name}`}><Trash2/></button></article>)}</section><aside className="order-summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>{money(cart.totals.subtotalCents)}</strong></div>{cart.totals.discountCents > 0 && <div className="discount"><span>Discount</span><strong>−{money(cart.totals.discountCents)}</strong></div>}<div><span>Estimated shipping</span><strong>{cart.totals.shippingCents ? money(cart.totals.shippingCents) : 'Free'}</strong></div><div><span>Estimated tax</span><strong>{money(cart.totals.taxCents)}</strong></div><div className="total"><span>Total</span><strong>{money(cart.totals.grandTotalCents)}</strong></div><form className="coupon" onSubmit={coupon}><label htmlFor="coupon">Promo code</label><div><input id="coupon" value={code} onChange={(e) => setCode(e.target.value)} placeholder="WELCOME15"/><button>Apply</button></div>{message && <small role="status">{message}</small>}</form><Link className="button full" to="/checkout">Secure checkout</Link><p className="fine-print">Totals are recalculated securely on the server before payment.</p></aside></div></main>;
}