import { Heart, Menu, Search, ShoppingBag, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useGetCartQuery, useMeQuery, useSubscribeNewsletterMutation } from '../app/api';

export const Layout = () => {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const navigate = useNavigate();
  const [subscribe] = useSubscribeNewsletterMutation(); const [newsletterMessage, setNewsletterMessage] = useState('');
  const { data: user } = useMeQuery(); const { data: cart } = useGetCartQuery(undefined, { skip: !user });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (search.trim()) navigate(`/shop?q=${encodeURIComponent(search.trim())}`); };
  return <div className="app-shell">
    <div className="announcement">Complimentary shipping on orders $75+ <span>•</span> Easy 30-day returns</div>
    <header className="site-header"><div className="header-inner"><button className="icon-button menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button><Link to="/" className="brand-mark">WELLORA <small>MARKET</small></Link><nav className={open ? 'main-nav open' : 'main-nav'} aria-label="Main navigation"><NavLink to="/shop" onClick={() => setOpen(false)}>Shop all</NavLink><NavLink to="/shop?category=skincare" onClick={() => setOpen(false)}>Skin</NavLink><NavLink to="/shop?category=hair-care" onClick={() => setOpen(false)}>Hair</NavLink><NavLink to="/shop?category=wellness" onClick={() => setOpen(false)}>Wellness</NavLink><NavLink to="/shop?sort=popular" onClick={() => setOpen(false)}>Best sellers</NavLink></nav><form className="header-search" onSubmit={submit}><Search size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} aria-label="Search products" placeholder="Search essentials" /></form><div className="header-actions"><Link to="/wishlist" aria-label="Wishlist"><Heart /></Link><Link to={user ? '/account' : '/login'} aria-label="Account"><UserRound /></Link><Link to="/cart" aria-label={`Cart with ${cart?.items.length ?? 0} items`} className="cart-link"><ShoppingBag /><span>{cart?.items.length ?? 0}</span></Link></div></div></header>
    <Outlet />
    <footer><div className="footer-grid"><div><Link to="/" className="brand-mark light">WELLORA <small>MARKET</small></Link><p>Considered essentials for beauty, personal care, and everyday wellness.</p></div><div><h3>Explore</h3><Link to="/shop">Shop all</Link><Link to="/shop?sort=newest">New arrivals</Link><Link to="/shop?sort=popular">Best sellers</Link></div><div><h3>Customer care</h3><Link to="/support">Contact us</Link><Link to="/legal/shipping">Shipping & returns</Link><Link to="/legal/privacy">Privacy</Link></div><div><h3>Stay in the know</h3><form className="newsletter" onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const email = String(new FormData(form).get('email')); try { const result = await subscribe(email).unwrap(); setNewsletterMessage(result.message); form.reset(); } catch { setNewsletterMessage('Subscription could not be saved.'); } }}><label htmlFor="newsletter">Monthly notes and new arrivals</label><div><input id="newsletter" name="email" type="email" required placeholder="you@example.com"/><button>Join</button></div>{newsletterMessage && <small role="status">{newsletterMessage}</small>}</form></div></div><div className="footer-bottom"><p>© 2026 Wellora Market. Independent retailer; no affiliation with third-party brands is implied.</p><p className="developer-credit">Developed by Mina Magdy</p></div></footer>
  </div>;
};